
IR Thermometer (IRT)
* [[http://www.mdpi.com/1424-8220/15/5/11387/htm][Determining the Leaf Emissivity of Three Crops by Infrared Thermometer]] 
** infrared thermometer + thermocouple wirE, simple and novel technique was developed to determine the emissivities of leaves for three horticultural crops using an infrared thermometer.
** Test guesses for emissivity by assuming constant distrubition of temp across plant
** Integrating across all wavelengths
** epsilon = 0.9809, 0.9783, 0.981, 0.9848 for Phalaenopsis mature and new leaves and Paphiopedilum and Malabar chestnut leaves
*** Experimental section
**** total rad = object + reflections + transmission
***** transmission isgnored
***** R_t = epsilon * alpha * T^4_leaf + (1 - epsilon) * alpha * T^4_ref_bckgnd [W/m-2]
***** E_ircam = epsiloThe target temperature for calibration was maintained at 10, 15, 20, 25, 30, 35 and 40 °C n_ircam * T^4_ircam_detected + E_error    (IR camera)
***** E_thermo = epsilon_thermo * T^4_thermo   (thermocouple)
***** assum E_ircam == E_thermo
***** assume epsilon_thermo = epsilon_ircam
**** Thermometers
***** The target temperature for calibration was maintained at 10, 15, 20, 25, 30, 35 and 40 deg C 
**** Measurement:
***** Done at Night for min radiation
***** thermocouple attached with permeable tape
***** measurements taken with syncronized thermocouple + IR

* [[http://hortsci.ashspublications.org/content/25/12/1535.full.pdf][Measuring Plant Stress with an Infrared Thermometer]]
** portable infrared thermometer to measure foliage temperature and calculate a crop water stress index (CWSI)
*** theory:
**** biological emissivity 0.9-0.99 in 105-12.5 um band, plants 0.97-0.99
**** shade for 20-30 sec changes temp significantly
**** compare T_foliage to T_air
***** look for transpiration loss, compare to well watered plant response
****** humid environments skew results negatively
*** "Recently,  foliage  temperatures  have  been  related  to  the  temperature  response  of  the  enzymes  within  the  plant.  Burke  and  Hatfield (1987)  showed  that  it  was  necessary  to  consider  the  foliage  temperature-enzyme  activity  relationship  to  fully  quantify  the  protection  level  of  glutathione  reductase  in  field-grown  wheat"
**** while night --> plant == air temp --> day --> temps good for enzyme function --> temp increase
***** dependednt on : soil water availability, net radiation, air temperatures
***** temp differences: 23-32 C (cotton), 10-17 C (spinach), 30-40 C (cucumber) between ait to plant
***** more variability as soil water decreased
***** flowers --> no transipration --> 5 C higher



* IR Camera
* [[https://academic.oup.com/jxb/article/53/378/2249/426550/Use-of-infrared-thermography-for-monitoring][Use of infrared thermography for monitoring stomatal closure in the field: application to grapevine]]
** method of monitoring stomatal closure of grapevines in the field with infrared thermography
*** wet and dry reference surfaces to eliminate non-leaves
**** Background:
***** Crop Water Stress Index CWSI --> determiine underwatered crops
****** issues: not useful in humid climates
****** if too broad, included non vegetation in measeaurement (soil)
***** Reference Surfaces allows for scaling of test for current conditions
****** assumes model and reference are similar
****** use wet or petroleum covered leaves for ensuring equivalent radioactive properties
***** "variation in temperature could be a more sensitive measure of mean leaf conductance than was mean temperature itself."
***** variation increases as stomata close
**** Imaging
***** "The background temperature required for calculation of object temperatures was estimated as the radiative temperature of a crumpled aluminium foil sheet placed in as similar as possible a position as the object being viewed, with emissivity set at 1.0; emissivity was set at 0.95 for viewing leaves."
***** subtracted correction by imagin with lens cap on at intervals during testing
**** Results
***** filter paper (wet/dry), leaves (wet/dry) 
****** set upper and lower bounds to image analysis
***** avg temps + freq distrubution of temps over area
***** greater variance for plants in sunlight 25% - 42% and with larger pixels
**** Illumination
***** "The sensitivity of Tleaf to changes in stomatal conductance, and hence the utility of thermal imaging for the study of stomatal conductance, depends both on the absorbed radiation and on the boundary layer conductance and atmospheric humidity."
***** sunlit leaves better for stomatal conductance
***** reference objects experienced high variance from small size and changing level of wetness
**** Energy Balance:
***** Temp Air-leaf
***** stomatal resistance --> leaf resistance to water vapour transfer
***** boundary layer resistance to water vapour
***** net isothermal radiation
***** air water vapour pressure deficit 
***** parallel resistance to heat and radaiative transfer
***** psychrometric constant
***** density of air
***** specific heat capascity of air
***** slope realtion saturation vapour pressure to temperatures
**** Atmospheric environment on canopy temperatures
***** slight variance in minute intervals
***** fluctuating reference leads to errors in results
**** Temp, water status, stress indices, stomatal conductance
***** difference in variation throughout day
***** treatments --> No irrigation, 100% ETC, 50% ETC 
***** "Much more surprising, however, was the observation that there were similar, or even stronger, highly consistent and significant treatment effects on both the reference temperatures (Tdry and Twet). "
***** Higher temps for No water and dry reference than for the 100% ETC or dry reference
***** reference materials AFFECTED by microclimate surounding the plants
****** No water may raise local temperature, soil heating
**** COnclusion
***** real leaves with water or petroleum jelly to stop transpiration

* [[https://academic.oup.com/jxb/article/55/401/1423/478977/Combining-thermal-and-visible-imagery-for][Combining thermal and visible imagery for estimating canopy temperature and identifying plant stress]]
** measured the temperature distribution of sunlit and shaded leaf area of Vinifera canopies, and then compared the effects of irrigation treatments
*** "The present method provides two major improvements compared with earlier methods for calculating thermal indices. First, it allows more accurate estimation of the indices, which are consequently more closely related to stomatal conductance. Second, it gives more accurate estimates of the temperature distribution of the shaded and sunlit parts of canopy, and, unlike the earlier methods, makes it possible to quantify the relationship between temperature variation and stomatal conductance."
*** Intro
**** evaporation, radiation, windspeed, air temperatures, air humidity all affect canopy temp
**** dry leaf --> no transipration surface (petroleum), wet leaf --> maximum transipration
**** treatments --> no water 2 day, no water 1 day, full water
*** measurements
**** stomatal conductance using porometer
**** (global and photosynthetically active radiation, air temperature, and relative humidity
*** Imaging
**** 8-12 um
**** NIR
**** Visible
*** Processing
**** background correction from lens cap imaging
**** supervised classification of plant vs not plant, sunlight vs shade

* [[http://ac.els-cdn.com/S003442579600123X/1-s2.0-S003442579600123X-main.pdf?_tid=e76aecf2-faf4-11e6-bf59-00000aacb361&acdnat=1487984224_10336d649a6a881b7156c62ceec13e7a][Emissivity measurements of several soils and vegetation types in the 8–14 μm wave band: analysis of two field methods.]]   
** emissivities for the Landsat Thematic Mapper band 6 and NOAA Advanced Very High Resolution Radiometer channels 4 and 5 have been derived
*** Background
**** Radiation summation of refection and emission
**** emissivity values in 10-12 um region higher than 8-14 um
**** field measurements of emissivities of ground surfaces
*** Methodology
**** Box Method
***** way of measeaurement of a sample
***** specularly reflective sides (epsilon=0.03)
***** different lids with small central hole to measure from
**** Two-Lid Method
***** hot lid --> rough anodized aluminum painted Parson's black --> perfect difusser (epsilon = 0.98)
***** cold lid --> specularly reflective polished aluminum --> epsilon = 0.03
***** three confidurations to measure radiance (L)
****** sample in box with cold lid --> two minutes acclimation --> measurement taken (L1)
****** once taken hot lid immediately switched with cold lid --> measeaurement taken (L2)
****** hot lid on top, cold lid on bottom --> material in cold center --> measeaurement taken (L3)
**** One-Lid Method
****** cold lid on top
****** no box at all 
****** reverse sensor to look at sky
*** Two Lid
**** theoretical
***** ideal --> epsilon_cold = 0, epsilon_hot = 1
***** epsilon_0 = (L3-L1)/(L3-L2)
***** epsilon_s = epsilon_0 + delta*epsilon (corrective factor)
***** perfect diffuser + reflectors same for total energy integrated --> direction changes
****** Lambertian walls would only allow half the incident to reach the top
****** cold lid also assumed Lambertian (even with epsilon=0.03) bc all directions incident are equal from walls
***** Assumes temp does not change during measurements
***** only energy from surface, and energy reflected from surface
***** only the base is directly measured through the through hole
***** solve for corrective factor
**** functional dependence of Emissivity
***** box size changes Transference Factor
****** F = 1 for infinitely large base area ( H/L=0)
****** F = 0 for near zero base area (H/L >> 1)
***** determine Tcold --> cold lid on bottom with small diffusive zone
****** also could just thermocouple
**** analysis of Sensitivity
***** primary --> sensitivity of radiometer

* [[emissivities for the Landsat Thematic Mapper band 6 and NOAA Advanced Very High Resolution Radiometer channels 4 and 5 have been derived][Determining the emissivity of the leaves of nine horticultural crops by means of infrared thermograpy]]
** hermographic camera was used for both qualitative and quantitative emissivity measurement by evaluating radiation emission from the leaves

* [[http://www.sciencedirect.com/science/article/pii/S0034425707000454][Spectral reflectance and emissivity features of broad leaf plants: Prospects for remote sensing in the thermal infrared (8.0–14.0 μm)]]
** "he data show, for the first time, that it is possible to discriminate subtle spectral emissivity features of leaves from the natural background emission."
*** Intro
**** "directional hemispherical reflectance (DHR) " --> unique spectra for each species
***** Used for calculating emissivity --> need to look at surface and volume scatter effects
****** results of both are opposite in sign
**** "attenuated total reflectance (ATR) " --> discern aspects of the cutiles and cell walls
***** provide measurements  similar to transmission measurements, avoid scatter problems
****** "ATR involves a surface evanescent wave that penetrates to only a few microns depth"
*** Methods
**** ATR wavelength span 2.5-15.38 um (4000 - 650 cm-1 freq) at 4 cm-1 resolution
**** DHR used integrating sphere --> internal reflectance 0.96 --> wavelength span 2.5 - 14 um
***** referenced against clean, crinkled aluminum (reduced specular characteristics), reflectance = 0.93
**** measurements completed in 10 min total, 0.1 C temp drift, low humidity, clear sky
***** spectral radiance calibrated with blackbodies at 10C and 40C
***** horizontal --> detached leaves carpeted FOV of spectrometer for uniform surface of leaves
****** once taken, high relfectivity plate put on top, to relfect downwelling radiance for measurement
***** in situ --> measurements of leave on branches
****** plate then placed directly beneath spectrometer
**** relfected solar energy and upwelling atmospheric path between sensor and object ignored
***** L_lambda = epsilon * L_BB + (1 - epsilon) * L_DWR
**** DHR Sequence:
***** 1.) T_s is sample temp (T_s, unknown) near abmient temp and used to normalize against Plank function (Black body approx)
***** 2.) Repeat for multiple BB temps
***** 3.) Check if trial temp > actual sample temp --> relfected downwelling radiance overcorrected --> residual features are opposite to those in the actual downwelling rad
***** 4.) iterate until residuals minimized
**** ATR In situ SEquence:
***** scale factor applied to downwelling radiance data
***** epsilon = (L - x * L_DWR ) / ( L_BB - x * L_DWR )
***** downwelling captured with aluminum covered panel --> not accurate --> x < 1.0 (0.9 better)
*** Results
**** Absorbtion 9.48 um, 9.70 um:
***** ATR: strong 
***** DHR: less prominent
****** two reflectence maxima --> surface scattering 
**** Absorbtion 8.61 um, 9.03 um:
***** ATR: moderate
***** DHR: moderate
****** surface scattering
**** Absorbtion 11.15 um:
***** ATR: weak
***** DHR: major reflectance minimum
****** volume scatter
**** DHR:
***** thickness of cellulose --> volume and/or surface scatter
**** Xylan (hemicellulose)
***** "Hemicelluloses are polysaccharides that form part of the matrix surrounding cellulose fibers of cell walls"
***** ATR spectrum xylan --> DHR spectrum Z. mays leaves --> mirror image (9.62 um)
****** strong surface scatter related to leaves with abundant xylan
**** Cutin
***** appears at 8.59, 9.07, 12.01, and 13.89 um
**** Silica
***** appears at 9.08, 12.36 um
**** Oleanolic Acid (terpenes)
***** broad class in several species
***** appears at 9.69, 10.03 um
**** Surface Effects
***** texture of waxes on upper and lower surfaces --> adaxial = smooth --> abaxial = cavities
***** difference of up to 4% reflectance



* Other

* Infrared Issues:
** background radiation
** values for the emissivity
** calibration of the infrared thermometer 
*** [[https://dl.sciencesocieties.org/publications/aj/pdfs/58/6/AJ0580060597][Infrared Thermometry of Vegetation]]
*** blackbody target incremented 0-50 C for calibration
**** blackbody cones in controlled water baths
