
IR Thermometer (IRT)
* [[http://www.mdpi.com/1424-8220/15/5/11387/htm][Determining the Leaf Emissivity of Three Crops by Infrared Thermometer]]
** infrared thermometer + thermocouple wirE, simple and novel technique was developed to determine the emissivities of leaves for three horticultural crops using an infrared thermometer.
** Test guesses for emissivity by assuming constant distrubition of temp across plant
** Integrating across all wavelengths
** epsilon = 0.9809, 0.9783, 0.981, 0.9848 for Phalaenopsis mature and new leaves and Paphiopedilum and Malabar chestnut leaves
*** Experimental section
**** total rad = object + reflections + transmission
***** transmission isgnored
***** R_t = epsilon * alpha * T^4_leaf + (1 - epsilon) * alpha * T^4_ref_bckgnd [W/m-2]
***** E_ircam = epsiloThe target temperature for calibration was maintained at 10, 15, 20, 25, 30, 35 and 40 °C n_ircam * T^4_ircam_detected + E_error    (IR camera)
***** E_thermo = epsilon_thermo * T^4_thermo   (thermocouple)
***** assum E_ircam == E_thermo
***** assume epsilon_thermo = epsilon_ircam
**** Thermometers
***** The target temperature for calibration was maintained at 10, 15, 20, 25, 30, 35 and 40 deg C
**** Measurement:
***** Done at Night for min radiation
***** thermocouple attached with permeable tape
***** measurements taken with syncronized thermocouple + IR

* [[http://hortsci.ashspublications.org/content/25/12/1535.full.pdf][Measuring Plant Stress with an Infrared Thermometer]]
** portable infrared thermometer to measure foliage temperature and calculate a crop water stress index (CWSI)
*** theory:
**** biological emissivity 0.9-0.99 in 105-12.5 um band, plants 0.97-0.99
**** shade for 20-30 sec changes temp significantly
**** compare T_foliage to T_air
***** look for transpiration loss, compare to well watered plant response
****** humid environments skew results negatively
*** "Recently,  foliage  temperatures  have  been  related  to  the  temperature  response  of  the  enzymes  within  the  plant.  Burke  and  Hatfield (1987)  showed  that  it  was  necessary  to  consider  the  foliage  temperature-enzyme  activity  relationship  to  fully  quantify  the  protection  level  of  glutathione  reductase  in  field-grown  wheat"
**** while night --> plant == air temp --> day --> temps good for enzyme function --> temp increase
***** dependednt on : soil water availability, net radiation, air temperatures
***** temp differences: 23-32 C (cotton), 10-17 C (spinach), 30-40 C (cucumber) between ait to plant
***** more variability as soil water decreased
***** flowers --> no transipration --> 5 C higher



* IR Camera
* [[https://academic.oup.com/jxb/article/53/378/2249/426550/Use-of-infrared-thermography-for-monitoring][Use of infrared thermography for monitoring stomatal closure in the field: application to grapevine]]
** method of monitoring stomatal closure of grapevines in the field with infrared thermography
*** wet and dry reference surfaces to eliminate non-leaves
**** Background:
***** Crop Water Stress Index CWSI --> determiine underwatered crops
****** issues: not useful in humid climates
****** if too broad, included non vegetation in measeaurement (soil)
***** Reference Surfaces allows for scaling of test for current conditions
****** assumes model and reference are similar
****** use wet or petroleum covered leaves for ensuring equivalent radioactive properties
***** "variation in temperature could be a more sensitive measure of mean leaf conductance than was mean temperature itself."
***** variation increases as stomata close
**** Imaging
***** "The background temperature required for calculation of object temperatures was estimated as the radiative temperature of a crumpled aluminium foil sheet placed in as similar as possible a position as the object being viewed, with emissivity set at 1.0; emissivity was set at 0.95 for viewing leaves."
***** subtracted correction by imagin with lens cap on at intervals during testing
**** Results
***** filter paper (wet/dry), leaves (wet/dry)
****** set upper and lower bounds to image analysis
***** avg temps + freq distrubution of temps over area
***** greater variance for plants in sunlight 25% - 42% and with larger pixels
**** Illumination
***** "The sensitivity of Tleaf to changes in stomatal conductance, and hence the utility of thermal imaging for the study of stomatal conductance, depends both on the absorbed radiation and on the boundary layer conductance and atmospheric humidity."
***** sunlit leaves better for stomatal conductance
***** reference objects experienced high variance from small size and changing level of wetness
**** Energy Balance:
***** Temp Air-leaf
***** stomatal resistance --> leaf resistance to water vapour transfer
***** boundary layer resistance to water vapour
***** net isothermal radiation
***** air water vapour pressure deficit
***** parallel resistance to heat and radaiative transfer
***** psychrometric constant
***** density of air
***** specific heat capascity of air
***** slope realtion saturation vapour pressure to temperatures
**** Atmospheric environment on canopy temperatures
***** slight variance in minute intervals
***** fluctuating reference leads to errors in results
**** Temp, water status, stress indices, stomatal conductance
***** difference in variation throughout day
***** treatments --> No irrigation, 100% ETC, 50% ETC
***** "Much more surprising, however, was the observation that there were similar, or even stronger, highly consistent and significant treatment effects on both the reference temperatures (Tdry and Twet). "
***** Higher temps for No water and dry reference than for the 100% ETC or dry reference
***** reference materials AFFECTED by microclimate surounding the plants
****** No water may raise local temperature, soil heating
**** COnclusion
***** real leaves with water or petroleum jelly to stop transpiration

* [[https://academic.oup.com/jxb/article/55/401/1423/478977/Combining-thermal-and-visible-imagery-for][Combining thermal and visible imagery for estimating canopy temperature and identifying plant stress]]
** measured the temperature distribution of sunlit and shaded leaf area of Vinifera canopies, and then compared the effects of irrigation treatments
*** "The present method provides two major improvements compared with earlier methods for calculating thermal indices. First, it allows more accurate estimation of the indices, which are consequently more closely related to stomatal conductance. Second, it gives more accurate estimates of the temperature distribution of the shaded and sunlit parts of canopy, and, unlike the earlier methods, makes it possible to quantify the relationship between temperature variation and stomatal conductance."
*** Intro
**** evaporation, radiation, windspeed, air temperatures, air humidity all affect canopy temp
**** dry leaf --> no transipration surface (petroleum), wet leaf --> maximum transipration
**** treatments --> no water 2 day, no water 1 day, full water
*** measurements
**** stomatal conductance using porometer
**** (global and photosynthetically active radiation, air temperature, and relative humidity
*** Imaging
**** 8-12 um
**** NIR
**** Visible
*** Processing
**** background correction from lens cap imaging
**** supervised classification of plant vs not plant, sunlight vs shade

* [[http://ac.els-cdn.com/S003442579600123X/1-s2.0-S003442579600123X-main.pdf?_tid=e76aecf2-faf4-11e6-bf59-00000aacb361&acdnat=1487984224_10336d649a6a881b7156c62ceec13e7a][Emissivity measurements of several soils and vegetation types in the 8–14 μm wave band: analysis of two field methods.]]
** emissivities for the Landsat Thematic Mapper band 6 and NOAA Advanced Very High Resolution Radiometer channels 4 and 5 have been derived
*** Background
**** Radiation summation of refection and emission
**** emissivity values in 10-12 um region higher than 8-14 um
**** field measurements of emissivities of ground surfaces
*** Methodology
**** Box Method
***** way of measeaurement of a sample
***** specularly reflective sides (epsilon=0.03)
***** different lids with small central hole to measure from
**** Two-Lid Method
***** hot lid --> rough anodized aluminum painted Parson's black --> perfect difusser (epsilon = 0.98)
***** cold lid --> specularly reflective polished aluminum --> epsilon = 0.03
***** three confidurations to measure radiance (L)
****** sample in box with cold lid --> two minutes acclimation --> measurement taken (L1)
****** once taken hot lid immediately switched with cold lid --> measeaurement taken (L2)
****** hot lid on top, cold lid on bottom --> material in cold center --> measeaurement taken (L3)
**** One-Lid Method
****** cold lid on top
****** no box at all
****** reverse sensor to look at sky
*** Two Lid
**** theoretical
***** ideal --> epsilon_cold = 0, epsilon_hot = 1
***** epsilon_0 = (L3-L1)/(L3-L2)
***** epsilon_s = epsilon_0 + delta*epsilon (corrective factor)
***** perfect diffuser + reflectors same for total energy integrated --> direction changes
****** Lambertian walls would only allow half the incident to reach the top
****** cold lid also assumed Lambertian (even with epsilon=0.03) bc all directions incident are equal from walls
***** Assumes temp does not change during measurements
***** only energy from surface, and energy reflected from surface
***** only the base is directly measured through the through hole
***** solve for corrective factor
**** functional dependence of Emissivity
***** box size changes Transference Factor
****** F = 1 for infinitely large base area ( H/L=0)
****** F = 0 for near zero base area (H/L >> 1)
***** determine Tcold --> cold lid on bottom with small diffusive zone
****** also could just thermocouple
**** analysis of Sensitivity
***** primary --> sensitivity of radiometer

* [[emissivities for the Landsat Thematic Mapper band 6 and NOAA Advanced Very High Resolution Radiometer channels 4 and 5 have been derived][Determining the emissivity of the leaves of nine horticultural crops by means of infrared thermograpy]]
** hermographic camera was used for both qualitative and quantitative emissivity measurement by evaluating radiation emission from the leaves

* [[http://www.sciencedirect.com/science/article/pii/S0034425707000454][Spectral reflectance and emissivity features of broad leaf plants: Prospects for remote sensing in the thermal infrared (8.0–14.0 μm)]]
** "he data show, for the first time, that it is possible to discriminate subtle spectral emissivity features of leaves from the natural background emission."
*** Intro
**** "directional hemispherical reflectance (DHR) " --> unique spectra for each species
***** Used for calculating emissivity --> need to look at surface and volume scatter effects
****** results of both are opposite in sign
**** "attenuated total reflectance (ATR) " --> discern aspects of the cutiles and cell walls
***** provide measurements  similar to transmission measurements, avoid scatter problems
****** "ATR involves a surface evanescent wave that penetrates to only a few microns depth"
*** Methods
**** ATR wavelength span 2.5-15.38 um (4000 - 650 cm-1 freq) at 4 cm-1 resolution
**** DHR used integrating sphere --> internal reflectance 0.96 --> wavelength span 2.5 - 14 um
***** referenced against clean, crinkled aluminum (reduced specular characteristics), reflectance = 0.93
**** measurements completed in 10 min total, 0.1 C temp drift, low humidity, clear sky
***** spectral radiance calibrated with blackbodies at 10C and 40C
***** horizontal --> detached leaves carpeted FOV of spectrometer for uniform surface of leaves
****** once taken, high relfectivity plate put on top, to relfect downwelling radiance for measurement
***** in situ --> measurements of leave on branches
****** plate then placed directly beneath spectrometer
**** relfected solar energy and upwelling atmospheric path between sensor and object ignored
***** L_lambda = epsilon * L_BB + (1 - epsilon) * L_DWR
**** DHR Sequence:
***** 1.) T_s is sample temp (T_s, unknown) near abmient temp and used to normalize against Plank function (Black body approx)
***** 2.) Repeat for multiple BB temps
***** 3.) Check if trial temp > actual sample temp --> relfected downwelling radiance overcorrected --> residual features are opposite to those in the actual downwelling rad
***** 4.) iterate until residuals minimized
**** ATR In situ SEquence:
***** scale factor applied to downwelling radiance data
***** epsilon = (L - x * L_DWR ) / ( L_BB - x * L_DWR )
***** downwelling captured with aluminum covered panel --> not accurate --> x < 1.0 (0.9 better)
*** Results
**** Absorbtion 9.48 um, 9.70 um:
***** ATR: strong
***** DHR: less prominent
****** two reflectence maxima --> surface scattering
**** Absorbtion 8.61 um, 9.03 um:
***** ATR: moderate
***** DHR: moderate
****** surface scattering
**** Absorbtion 11.15 um:
***** ATR: weak
***** DHR: major reflectance minimum
****** volume scatter
**** DHR:
***** thickness of cellulose --> volume and/or surface scatter
**** Xylan (hemicellulose)
***** "Hemicelluloses are polysaccharides that form part of the matrix surrounding cellulose fibers of cell walls"
***** ATR spectrum xylan --> DHR spectrum Z. mays leaves --> mirror image (9.62 um)
****** strong surface scatter related to leaves with abundant xylan
**** Cutin
***** appears at 8.59, 9.07, 12.01, and 13.89 um
**** Silica
***** appears at 9.08, 12.36 um
**** Oleanolic Acid (terpenes)
***** broad class in several species
***** appears at 9.69, 10.03 um
**** Surface Effects
***** texture of waxes on upper and lower surfaces --> adaxial = smooth --> abaxial = cavities
***** difference of up to 4% reflectance

* Energy Balance
** Transpiration
*** lambaE = R_n - G - H --> amount of energy aabsorbed during the conversion of liquid water to vapor
**** lambdaE: phase change energy (out of the plant)
**** R_n: net radiation (into the plant)
**** G: soil heat flux (into the ground)
**** H: sensible heat flux --> H = mc\delta{T} --> directly affects the temperature (out of plant)
******* https://en.wikipedia.org/wiki/Evapotranspiration
******* https://en.wikipedia.org/wiki/METRIC
*** boundary layer of air along surface of leaf, water vapor must cross this boundary.
**** moving air == faster transpiration
**** layer increases with leaf size --> decrease in transpiration
**** warm, dry, windy air causes higher transpiration
**** sunlight (even small) casues higher also
***** wet leaf has no transpiration
***** IGORES METABOLIC
******* http://passel.unl.edu/pages/informationmodule.php?idinformationmodule=1092853841&topicorder=6
*** Porometry --> chamber enclosing leaves to measure humidity increase
** Daltons LAw
*** he rate of evaporation is proportional to the difference between the stauration vapour pressure at the water temperature, e_s and the actual vapour pressure in the air e_a
**** E = K(e_S-e_a) --> rate of evaporation
***** e_s: saturation vapour pressure of air
***** e_a: actual vapour pressure of air
*** Energy Budget
**** E = ( Hn - Hg - Hs - Hi ) / (delta * L(1 + Beta) )
***** Hn: net heat energy recieved by water surface --> Hn = Hc(1-r) - Hb
***** Hc(1-r): incoming solar radiation into a surface of reflection coefficient, r
***** Hb: back radiation from water body
***** Hg: heat flux into the ground
***** Hs: heat stored in water body
***** Hi: net heat conducted out of the system by water flow
***** Beta: Bowen's ratio --> ratio of sensible to latent heat
***** Delta: density of water
***** L: Latent heat of evaporation
******* https://gradeup.co/evaporation-transpiration-and-stream-flow-measurement-i-978c41c5-8170-11e6-90ce-d2449cc97707
******* http://swhydro.arizona.edu/archive/V7_N1/feature3.pdf
** Latent Heat
******* http://plantsinaction.science.uq.edu.au/edition1/?q=content/14-5-plant-heat-budgets
*** "When solar radiation strikes a leaf (Figure 14.18), some is reflected, some is absorbed and some is transmitted. Absorbed energy is subsequently dissipated via three main avenues: reradiation of long wavelengths to nearby surfaces and sky; conduction and convection of sensible heat (directly measurable or able to be ‘sensed’); and latent heat exchange (energy consumed to evaporate water and commonly referred to as transpirational cooling)."
**** Reflection
***** Maimum in NIR (0.75-1.0 um) due to thick cuticle or dense pubescence (most 25% reflectance)
**** Sensible Heat
***** conduction with surrounding air through boundary layer. Relationship of leaf size and air speed
**** Latent Heat
***** partial pressure differences in plant internal and ambient. internal is saturation vapour pressure, outside ity

** Simultaneous Determination of sensible and latent heat transfer
******* http://download.springer.com/static/pdf/639/art%253A10.1007%252FBF02166806.pdf?originUrl=http%3A%2F%2Flink.springer.com%2Farticle%2F10.1007%2FBF02166806&token2=exp=1495216900~acl=%2Fstatic%2Fpdf%2F639%2Fart%25253A10.1007%25252FBF02166806.pdf%3ForiginUrl%3Dhttp%253A%252F%252Flink.springer.com%252Farticle%252F10.1007%252FBF02166806*~hmac=ac6c27b7c2d3c9412674cd5ac7f73d57fb2c04208fd0c91a2a9a76061878303c

* Links to investigate
*** http://sfrc.ufl.edu/facultysites/martin/pubs/Martin%20et%20al%201999.pdf
*** http://nature.berkeley.edu/ahg/pubs/Energy2.pdf
*** https://link.springer.com/article/10.1007/BF02166806
* Other

** Modeling Plant energy exchange
******* http://soils.wisc.edu/facstaff/wayne/cupid/outline.html#rbound

* Infrared Issues:
** background radiation
** values for the emissivity
** calibration of the infrared thermometer
*** [[https://dl.sciencesocieties.org/publications/aj/pdfs/58/6/AJ0580060597][Infrared Thermometry of Vegetation]]
*** blackbody target incremented 0-50 C for calibration
**** blackbody cones in controlled water baths

* Plant Motion
** Vines --> Wikipedia: https://en.wikipedia.org/wiki/Climbing_plant#cite_note-12
*** "It has also been suggested that twining vines revolving growth is mediated by changes in turgor pressure mediated by volume changes in the epidermal cells of the bending zone"
** Nutation --> Wikipedia: https://en.wikipedia.org/wiki/Nutation_in_plants
*** "Nutation is the bending movements executed by some plant organs, such as stems, leaves, roots, etc., by which the part is inclined successively in various directions"
*** Circiular motion "..in contrast to variation movements or movements produced by reversible turgor changes."
**** Turgor Pressure --> Wikipedia https://en.wikipedia.org/wiki/Turgor_pressure
***** "turgor pressure is caused by the osmotic flow of water and occurs in plants, fungi, and bacteria."
***** "Turgor pressure within cells is regulated by osmosis and also causes the cell wall to expand during growth. Along with size, rigidity of the cell is also caused by turgor pressure; a lower pressure results in a wilted cell or plant structure (i.e. leaf, stalk)"
** Plant movemnt: http://www.abc.net.au/science/articles/2010/09/30/3025894.htm
*** Phototropism: "If light is coming from the right, auxin gets sent down the left (shady) side of the shoot. That makes the cells on the shady side grow longer, putting a kink in the shoot so it points to the light. "
*** "t's this combination of wilting and swelling in different parts of the plant that act as levers and create movement, much like the extension and contraction of opposite muscles in our bodies that gets our limbs jumping. "
*** "And the driver for these movements is a tiny organ called the pulvinus that sits at the base of leaves and stems that fold. "
** Circumnutation  in Phaseolus vulgaris. I.  Growth,  osmotic  potential and  cell ultrastructure  in  the  free-moving  part  of  the  shoot : http://onlinelibrary.wiley.com/doi/10.1111/j.1399-3054.1988.tb06634.x/pdf
*** Nutation only possible with cell growth and cell elongation
*** osmotic potential of ~70mOsm between convex/concave side of vine
*** "During  every revolution,  each  cell  alternately swelled  and shrunk.  When turgor pressure was high, the deposits on the microfibril  would  be dense, when  turgor pressure was low they would be thin"
*** " As  mentioned  above,  24  h  were  necessary  for  the displacement  upwards  of  the  bending  zone.  Since  the period  of  the  movement  was 90 min  (at  25°C) the  shoot completed  16 revolutions  in that time span. Thus in 24 h one  cell  was  16 times  in  the  convex  generatrix,  that  is it was very  turgid  16 times.  The  same  cell  was  also  in  the concave  generatrix  16 times,  that  is,  much  less  turgid. Thus,  in the bending zone, cells inflated  and deflated  16 times  a day."
** Heat Generation in Plants: http://www.plantphysiol.org/content/114/4/1137.full.pdf
** Overview of climbing plants: http://www.amjbot.org/content/96/7/1205.full.pdf+html
** Plant metabolism: http://www.biology-online.org/11/9_plant_metabolism.htm
*** Photosynthesis --> carbon + water + light energy == glucose + oxygen + water
**** two sucessive processes --> light reaction + carbon-fixing reactio
*** Respiration --> glusoce + enzymes == ethyl alcohol + carbon dioxide + ATP 2

* Jerzy
** Biologially Inspired vine-Like and Tendril-Like Robots: http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=7237221
** Tendril-Based Climbing Plants to Model, Simulate and Create Bio-Inspired Robotic Systems: http://www.sciencedirect.com/science/article/pii/S1672652914601177
** Microtubules, MAPS and plant directional cell expansion: https://www.researchgate.net/profile/John_Sedbrook/publication/5384840_Microtubules_MAPs_and_plant_directional_cell_expansion/links/565ef50d08ae4988a7bd9224.pdf
** Passonionfruit: https://www.hort.purdue.edu/newcrop/morton/passionfruit.html
** The global trend in plant twining direction: http://onlinelibrary.wiley.com/doi/10.1111/j.1466-8238.2007.00326.x/full
** Development at a Glance Phyllotaxis: http://dev.biologists.org/content/140/2/249.short
** Gelatinous fibers are widespread in coiling tendrils and twining vines: http://www.amjbot.org/content/96/4/719.full.pdf&sa=U&ei=FR9rU8ywDePJ8wHJ-4Ew&ved=0CBsQFjAA&usg=AFQjCNE9Ano8tm5XsTQSmeLFEPFnMBoz1Q
** A cortical band of gelatinous fibers causes the coiling of redvine tendrils: a model based upon cytochemical and immunocytochemical studies: https://link.springer.com/article/10.1007/s00425-006-0363-4
** Physiological Studies on Pea Tendrils VIII. The Relationship of Circumnutation to Contact Coiling. — With a Description of a Laboratory Intervalometer Using Integrated Digital Circuits: http://onlinelibrary.wiley.com/doi/10.1111/j.1399-3054.1972.tb03548.x/full
** Helical growth in plant organs: mechanisms and significance: http://dev.biologists.org/content/143/18/3272
** mechanisms of tendrils motion in vines: https://books.google.com/books?hl=en&lr=&id=Z11Og4ipYHQC&oi=fnd&pg=PA1&dq=mechanisms+of+tendrils+motion+in+vines+&ots=kViKHSQrO4&sig=vkTXwX4RT19sZWcRrySpIazaLuc#v=onepage&q=mechanisms%20of%20tendrils%20motion%20in%20vines&f=false
